apiVersion: apps/v1
kind: Deployment
metadata:
  name: arjun
  labels:
    tier: fullstack
spec:
  selector:
    matchLabels:
      tier: fullstack
  template:
    metadata:
      name: simplepod
      labels:
        tier: fullstack
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 100
