apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    tier: apigateway
    app: apigateway
spec:
  selector:
    matchLabels:
      tier: fullstack
  template:
    metadata:
      name: nginx-pod
      labels:
        tier: apigateway
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 20
