apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      name: node-pod
      labels:
        tier: backend
    spec:
      containers:
        - name: node-container
          image: node
  replicas: 10
